### ISSUE TITLE
json to terraform code

### ISSUE THREAD

**Issue by iahmad-khan** [pulse-vadc/terraform-provider-vtm#10]
I am trying to convert all the existing configuration to terraform , and wonder if there is some way to convert the json representation of existing resources into terraform code?

**Comment by ndavidson-pulse** [comment]
Hi Iahmad, have you read about Terrafom's import functionality? https://www.terraform.io/docs/import/index.html can be useful in gradually adopting infrastructure into terraform.

**Comment by iahmad-khan** [comment]
Hi,

If I write the code for existing resources with same values and push it, it
will overwrite the resources in vtm?  Is it safe to do so?

**Comment by ndavidson-pulse** [comment]
Yes apply from Terraform will overwrite the existing resources. 

You can use the diff from terraform plan without apply to check that nothing unexpected is going to change and that your resource definition is complete.

Terraform like many dev-ops style solutions doesn't expect resources to change under its feet, but by paying careful attention to the output of plan / apply you should be able to tell if you've missed a setting in your resource definition or if someone changes the resources directly after you've migrated some of the configuration.

If you're considering gradually  migrating a manually managed vtm into terraform then the following strategy may help:
* Make sure every administrator of the vTM knows what you''re planning to do.
* Rename the resource you intend to migrate, adding a suffix or prefix you've previously agreed indicate it is a resource now managed by terraform. This also helps identify which resources have already been migrated.
* Ensure only truly shared resources are shared - SSL certs generally should only have a single copy on the vTM, but rules can be deployed from a static file or a using a terraform template_file (https://www.terraform.io/docs/providers/template/d/file.html) and made unique using the name of the owning virtual server so that every virtual server that uses a rule gets its own copy.. This can help if you need to change a rule for only a subset of the virtual servers using it. 

For example if you are intending to migrate the virtual server ```staging_vs```, rule ```ssl_redirect``` and pool ```staging_pool``` you could add the ```tf_``` prefix so they become: ```tf_staging_vs```, ```tf_staging_ssl_redirect``` and ```tf_staging_pool```.
