### ISSUE TITLE
Docker image for major releases

### ISSUE THREAD

**Issue by iahmad-khan** [pulse-vadc/terraform-provider-vtm#3]
Hi,

We are using the Licensed version of Pulse VTM , and we need to integrate it with Kubernetes , it will be very useful if there are official docker images of this provider so that we can just pull the image with required API/Release tag and run it. 

Thanks

**Comment by mgeldert** [comment]
Hi @iahmad-khan, and thanks for filing this issue.  

Please could you give us some more details about the workflow you envisage with a Docker container?  Since the provider is only executed on-demand, via the terraform command, there is nothing to "run" in a long-lived container.  Are you thinking of a container that would be deployed and passed a template to action, before exiting?  Or perhaps a generic Linux container with Terraform and the provider pre-installed, on which you can exec terraform commands?  The better we can understand your use-cases/workflows, the better we can evaluate potential solutions for you.

Thanks,

Matt

**Comment by iahmad-khan** [comment]
Hi

Yes, I just want to mount my files and run/exec terraform in container. So
that I don't have to set up anything. I'm currently working on dockerfile,
but have not tested it yet, official images for all tags would be better.

**Comment by mgeldert** [comment]
Thanks.  We'll add this to our internal feature request list and provide updates here as they become available.

**Comment by pillalamarriramana** [comment]
We've provided linux binaries with releases.
Docker image is not under consideration.
